# Generated by Django 4.1.7 on 2024-07-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartdata',
            old_name='number',
            new_name='rate',
        ),
    ]
